# Generated by Django 2.1.4 on 2019-01-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=264, unique=True)),
                ('web_url', models.URLField(unique=True)),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_demo.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='web_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_demo.Webpage'),
        ),
    ]
